app/__init__.py
from flask import Flask, current_app
from flask_restful import Api
from subprocess import Popen, PIPE, SubprocessError
import json, sys, shlex, os
from config import Config

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    from app.api import bp as api_bp
    app.register_blueprint(api_bp)
    
    from app.errors import bp as errors_bp
    app.register_blueprint(errors_bp)

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

def storjshare_status():
    try:
        args = shlex.split(os.environ.get('STORJSHARE_PATH', '/home/storj/node_modules/.bin/storjshare') + ' status -j')
        current_app.logger.debug('args: ' + str(args))

        proc = Popen(args, stdout=PIPE, stderr=PIPE)
        out, err = proc.communicate()
        exitcode = proc.returncode
        current_app.logger.debug('storjshare process raw output: %s', out)
        current_app.logger.debug('storjshare process error: %s', err)
        current_app.logger.debug('storjshare process exitcode: %s', exitcode)

        j = json.loads(out.decode('utf-8').strip())
        current_app.logger.debug('json raw output: %s', str(j))
        return j

    except UnicodeDecodeError as err: 
        current_app.logger.error('Unable to decode unicode data from process: %s', str(err))
        return {"error": "Unable to decode unicode data from process", "exception": str(err)}
    except json.decoder.JSONDecodeError as err:
        current_app.logger.error('Unable to decode json data: %s', str(err))
        return {"error": "Unable to decode json data", "exception": str(err)}
    except FileNotFoundError as err:
        current_app.logger.error('Storjshare path is invalid: %s', str(err))
        return {"error": "Storjshare path is invalid", "exception": str(err)}
    except:
        exc_type, exc_obj, exc_tb = sys.exc_info()
        fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
        err = exc_type, fname, exc_tb.tb_lineno
        current_app.logger.error('An unknown error has occurred: %s', str(err))
        return {"error": "Unexpected error", "exception": str(err)}

app/api/__init__.py
from flask import Blueprint

bp = Blueprint('api', __name__)

from app.api import resources

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, current_app
from app.main import bp
from app import storjshare_status

@bp.route('/')
@bp.route('/index')
def index():
    j = storjshare_status()
    return render_template('dashboard/dashboard.html', storjNodes=j, title='StorjStat')

app/templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% include 'components/head.html' %}
  </head>

  <body>
    {% include 'components/nav.html' %}

    <div class="container-fluid">
      <div class="row">
        {% include 'components/sidebar.html' %}

        {% block content %}{% endblock %}
      </div>
    </div>

    {% include 'components/ending-scripts.html' %}
  </body>
</html>

app/templates/components/ending-scripts.html
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.min.js" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" crossorigin="anonymous"></script>

<!-- Icons -->
<script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
<script>feather.replace()</script>

<!-- Graphs -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.1/Chart.min.js"></script>
<script>
  var ctx = document.getElementById("myChart");
  var myChart = new Chart(ctx, {
    type: 'line',
    data: {
      labels: ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"],
      datasets: [{
        data: [15339, 21345, 18483, 24003, 23489, 24092, 12034],
        lineTension: 0,
        backgroundColor: 'transparent',
        borderColor: '#007bff',
        borderWidth: 4,
        pointBackgroundColor: '#007bff'
      }]
    },
    options: {
      scales: {
        yAxes: [{
          ticks: {
            beginAtZero: false
          }
        }]
      },
      legend: {
        display: false,
      }
    }
  });
</script>

app/templates/components/head.html
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="">
<meta name="author" content="">
<title>StorjStat Dashboard</title>

<!-- Bootstrap CSS -->
<link href="https://stackpath.bootstrapcdn.com/bootswatch/4.1.0/solar/bootstrap.min.css" rel="stylesheet" type="text/css" crossorigin="anonymous">

<!-- Custom styles for this template -->
<link href="{{ url_for('static', filename='dashboard/dashboard.css') }}" rel="stylesheet" type="text/css" crossorigin="anonymous">

app/templates/components/nav.html
<nav class="navbar navbar-dark fixed-top sticky-top bg-dark p-0 shadow">
  <div class="nav flex-sm-nowrap flex-md-nowrap flex-lg-nowrap w-100">
    <div class="nav col-sm-3 col-md-2 m-0 p-0 flex-nowrap">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggler" aria-controls="navbarToggler" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand w-100 mr-0 text-center" href="{{ url_for('main.index') }}">{{ title }}</a>
    </div>

    <div class="nav flex-nowrap w-100">
      <input class="form-control form-control-dark" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </div>
  </div>

  <div class="collapse navbar-collapse fixed-top mt-5" id="navbarToggler">
    <ul class="navbar-nav text-center">
      <li class="nav-item">
        <a class="nav-link text-light bg-dark" href="{{ url_for('main.index') }}">
            <span data-feather="home"></span>
            Dashboard <span class="sr-only">(current)</span>
        </a>
      </li>
      <li class="nav-item">
          <a class="nav-link text-light bg-dark" href="{{ url_for('api.get_status') }}">
              <span data-feather="box"></span>
              API <span class="sr-only">(current)</span>
          </a>
      </li>
    </ul>
  </div>
</nav>

app/templates/components/sidebar.html
<nav class="col-md-2 d-none d-md-block bg-light sidebar">
    <div class="sidebar-sticky bg-dark">
        <ul class="nav flex-column">
            <li class="nav-item">
                <a class="nav-link text-light bg-dark" href="{{ url_for('main.index') }}">
                    <span data-feather="home"></span>
                    Dashboard <span class="sr-only">(current)</span>
                </a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-light bg-dark" href="{{ url_for('api.get_status') }}">
                    <span data-feather="box"></span>
                    API <span class="sr-only">(current)</span>
                </a>
            </li>
        </ul>
    </div>
</nav>

app/templates/dashboard/dashboard.html
{% extends "base.html" %}
{% block content %}
<main role="main" class="col-md-10 col-lg-10 ml-auto px-5 py-0">
  <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
    <h1 class="h2">Dashboard</h1>
    <div class="btn-toolbar mb-2 mb-md-0">
      <div class="btn-group mr-2">
        <button class="btn btn-sm btn-outline-secondary">Share</button>
        <button class="btn btn-sm btn-outline-secondary">Export</button>
      </div>
      <button class="btn btn-sm btn-outline-secondary dropdown-toggle">
        <span data-feather="calendar"></span>
        This week
      </button>
    </div>
  </div>

  <canvas class="w-100" id="myChart" width="900" height="380"></canvas>

  <h2>Details</h2>
  <div class="table-responsive ">
    <table class="table table-striped table-sm text-nowrap">
      <thead>
        <tr>
          <th>Node ID</th>
          <th>Status</th>
          <th>Uptime</th>
          <th>Shared</th>
          <th>Peers</th>
          <th>Allocs</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          {% for node in storjNodes %}
          <td>{{ node.id }}</td>
          <td>{{ node.status }}</td>
          <td>{{ node.uptime }}</td>
          <td>{{ node.shared }}</td>
          <td>{{ node.peers }}</td>
          <td>{{ node.allocs }} / {{ node.dataReceivedCount }}</td>
          {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
</main>
{% endblock %}